name: RedvBlue
version: '${project.version}'
main: me.stephenminer.redvblue.RedBlue
api-version: 1.19
authors: [ stephenminer, meep ]
commands:
  arenaWand:
  setRerouteLoc:
  wallWand:
  joinRvB:
  leaveRvB:
  arena:
  reloadRvB:
  setWallTime:
  setMinPlayers:
  lootChest:
  forceRvb:
  rvbGive:
