name: RedvBlue
version: '${project.version}'
main: me.stephenminer.redvblue.RedBlue
api-version: 1.21
authors: [ stephenminer, meep, compewper ]
commands:
  rvb:

  rvbconfig:
    permission: "rvb.commands.config"

  rvbgive:
    permission: "rvb.commands.give"
  
  rvbarena:
    permission: "rvb.commands.arena"
  rvbchest:
    permission: "rvb.commands.lootchest"
  rvbloot:
    permission: "rvb.commands.lootchest"
