name: RedvBlue
version: '${project.version}'
main: me.stephenminer.redvsblue.RedVsBlue
api-version: 1.21
authors: [ stephenminer, meep, compewper ]
commands:
  rvb:

  rvbconfig:
    permission: "rvb.commands.config"

  rvbgive:
    permission: "rvb.commands.give"
  
  rvbchest:
    permission: "rvb.commands.lootchest"
  rvbloot:
    permission: "rvb.commands.lootchest"
